#!/usr/bin/env python3
"""Generate deterministic dirblock configuration."""

from __future__ import annotations

import argparse
import os
import shutil
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable


ROOT = Path(__file__).resolve().parent
CONFIG_DIR = ROOT / "config"
OUTPUT = CONFIG_DIR / "dirblock.toml"
DEFAULT_OUTPUT = CONFIG_DIR / "dirblock_default.toml"
HOME = Path.home()


@dataclass(frozen=True)
class Entry:
    value: str | None = None
    command: str | None = None
    standard_paths: tuple[str, ...] = ()
    suffix: str = ""
    filter: str | None = None
    comment: str | None = None
    missing_comment: str = "not found"


@dataclass(frozen=True)
class Watch:
    path: str
    title: str
    entries: tuple[Entry, ...]
    check_paths: tuple[str, ...] = ()
    always_render: bool = False


@dataclass
class RenderedEntry:
    value: str
    active: bool
    comment: str | None = None


@dataclass
class RenderContext:
    default_template: bool = False
    warnings: list[str] = field(default_factory=list)

    def warn(self, message: str) -> None:
        self.warnings.append(message)


HOST_HEADER = """# dirblock configuration
# Generated by generate_config.py.
# Each key under [watched] is a directory to protect.
# Value is a list of allowed binary paths. /proc/pid/exe is checked against these.
#   - Exact path:  "/usr/bin/ssh"
#   - Prefix match: "/usr/local/aws-cli/" (trailing slash)
#     Matches any exe under that directory. Useful for symlinks, versioned installs,
#     AppImage extract dirs, Snap revisions, and tools that update in place.
#   - Cmdline filter: "filter:path" — exe must match path AND /proc/pid/cmdline
#     must contain "filter".
#   - Ancestry profile: "path;profile" — exe is allowed only if every ancestor in
#     the ppid chain is in the named [profiles] section.
# Paths starting with ~ are expanded to the real user's home directory.
#
# This file intentionally includes common variants. Missing exact paths are
# commented out for the target host by this generator.

# [profiles]
# Profile entries are executable paths or prefix directories only. They are not recursive.
# "desktop_shell" = [
#     "/usr/lib/systemd/systemd",
#     "/usr/bin/kitty",
#     "/bin/bash",
# ]

[profiles]
\"remote_ssh\" = [
    \"/bin/bash\",
    \"/usr/bin/bash\",
    \"/usr/bin/tmux\",
    \"/usr/sbin/sshd\",
    \"/usr/bin/sshd\",
]

[general]
# Send desktop notifications on deny (requires notify-send).
notify = false

[watched]
"""

DEFAULT_HEADER = """# dirblock default configuration
# Generated by generate_config.py --default.
# Each key under [watched] is a directory to protect.
# Value is a list of allowed binary paths. /proc/pid/exe is checked against these.
#   - Exact path:  "/usr/bin/ssh"
#   - Prefix match: "/usr/local/aws-cli/" (trailing slash)
#     Matches any exe under that directory. Useful for symlinks, versioned installs,
#     AppImage extract dirs, Snap revisions, and tools that update in place.
#   - Cmdline filter: "filter:path" — exe must match path AND /proc/pid/cmdline
#     must contain "filter".
#   - Ancestry profile: "path;profile" — exe is allowed only if every ancestor in
#     the ppid chain is in the named [profiles] section.
# Paths starting with ~ are expanded to the real user's home directory.
#
# This file intentionally includes common variants. Run generate_config.py without
# --default to produce a target-host config with missing exact paths commented out.

# [profiles]
# Profile entries are executable paths or prefix directories only. They are not recursive.
# "desktop_shell" = [
#     "/usr/lib/systemd/systemd",
#     "/usr/bin/kitty",
#     "/bin/bash",
# ]

[profiles]
"remote_ssh" = [
    "/bin/bash",
    "/usr/bin/bash",
    "/usr/bin/tmux",
    "/usr/sbin/sshd",
    "/usr/bin/sshd",
]

[general]
# Send desktop notifications on deny (requires notify-send).
notify = false

[watched]
"""

COMMON_SECTION = """# ==============================================================================
# COMMON POLICY
# =============================================================================="""

LOCAL_SECTION = """# ==============================================================================
# AI / EDITOR POLICY
# =============================================================================="""

OPTIONAL_SECTION = """# ==============================================================================
# OPTIONAL HIGH-NOISE POLICY
# =============================================================================="""


COMMON_WATCHES: tuple[Watch, ...] = (
    Watch(
        path="~/.config/dirblock",
        title="dirblock's own config",
        entries=(
            Entry(value="~/.local/bin/dirblock"),
            Entry(value="/usr/local/bin/dirblock"),
            Entry(value="/usr/bin/dirblock"),
            Entry(value="/usr/lib/openssh/sftp-server", comment="Debian/Ubuntu sshfs writes"),
            Entry(value="/usr/libexec/openssh/sftp-server", comment="Fedora/RHEL/OpenSSH variant"),
        ),
    ),
    Watch(
        path="~/.ssh",
        title="SSH keys, known_hosts, config",
        entries=(
            Entry(command="sshd", standard_paths=("/usr/sbin/sshd", "/usr/bin/sshd"), comment="required for incoming SSH authorized_keys reads"),
            Entry(command="ssh", standard_paths=("/usr/bin/ssh",)),
            Entry(command="ssh-agent", standard_paths=("/usr/bin/ssh-agent",)),
            Entry(command="ssh-add", standard_paths=("/usr/bin/ssh-add",)),
            Entry(command="ssh-keygen", standard_paths=("/usr/bin/ssh-keygen",)),
            Entry(command="scp", standard_paths=("/usr/bin/scp",)),
            Entry(command="sftp", standard_paths=("/usr/bin/sftp",)),
            Entry(command="rsync", standard_paths=("/usr/bin/rsync",)),
            Entry(command="mosh", standard_paths=("/usr/bin/mosh",)),
            Entry(command="git", standard_paths=("/usr/bin/git", "/usr/local/bin/git")),
            Entry(value="/usr/lib/git-core/git"),
            Entry(value="/usr/lib/git-core/git-remote-http"),
            Entry(value="/usr/lib/git-core/git-remote-https"),
            Entry(value="/usr/libexec/git-core/git"),
            Entry(value="/usr/libexec/git-core/git-remote-http"),
            Entry(value="/usr/libexec/git-core/git-remote-https"),
            Entry(value="/usr/local/share/git-core/git"),
            Entry(value="/usr/local/share/git-core/git-remote-http"),
            Entry(value="/usr/local/share/git-core/git-remote-https"),
            Entry(command="cat", standard_paths=("/usr/bin/cat",), suffix=";dirblock"),
            Entry(command="cat", standard_paths=("/usr/bin/cat",), suffix=";remote_ssh"),
            Entry(command="less", standard_paths=("/usr/bin/less",), suffix=";dirblock"),
            Entry(command="less", standard_paths=("/usr/bin/less",), suffix=";remote_ssh"),
            Entry(command="vim", standard_paths=("/usr/bin/vim",), suffix=";dirblock"),
            Entry(command="vim", standard_paths=("/usr/bin/vim",), suffix=";remote_ssh"),
            Entry(command="nvim", standard_paths=("/usr/bin/nvim",), suffix=";dirblock"),
            Entry(command="nvim", standard_paths=("/usr/bin/nvim",), suffix=";remote_ssh"),
        ),
    ),
    Watch(
        path="~/.gnupg",
        title="GPG keys, trustdb",
        entries=(
            Entry(command="gpg", standard_paths=("/usr/bin/gpg",)),
            Entry(command="gpg-agent", standard_paths=("/usr/bin/gpg-agent",)),
            Entry(command="gpg2", standard_paths=("/usr/bin/gpg2",)),
            Entry(command="gpgconf", standard_paths=("/usr/bin/gpgconf",)),
            Entry(command="gpgsm", standard_paths=("/usr/bin/gpgsm",)),
            Entry(value="/usr/lib/gnupg/", comment="keyboxd/scdaemon and other GnuPG helpers"),
            Entry(value="/usr/libexec/gnupg/", comment="Fedora/RHEL helper variant"),
            Entry(command="pass", standard_paths=("/usr/bin/pass",)),
            Entry(command="gopass", standard_paths=("/usr/bin/gopass",)),
        ),
    ),
    Watch(
        path="~/.aws",
        title="AWS credentials",
        entries=(
            Entry(command="aws", standard_paths=("/usr/bin/aws", "/usr/local/bin/aws")),
            Entry(value="~/.local/bin/aws"),
            Entry(value="/usr/local/aws-cli/", comment="AWS CLI v2 bundle resolves under this prefix"),
            Entry(value="aws:~/.local/pipx/venvs/awscli/"),
            Entry(value="aws:~/.pyenv/versions/", comment="pip-installed AWS CLI under pyenv Python"),
            Entry(value="aws:~/.nvm/versions/node/"),
            Entry(value="aws:/usr/bin/node"),
        ),
        check_paths=("~/.aws/credentials",),
    ),
    Watch(
        path="~/.kube",
        title="Kubernetes config",
        entries=(
            Entry(command="kubectl", standard_paths=("/usr/bin/kubectl", "/usr/local/bin/kubectl")),
            Entry(value="~/.local/bin/kubectl"),
            Entry(value="/snap/kubectl/"),
            Entry(command="helm", standard_paths=("/usr/bin/helm", "/usr/local/bin/helm")),
            Entry(value="~/.local/bin/helm"),
            Entry(value="/snap/helm/"),
            Entry(command="k9s", standard_paths=("/usr/bin/k9s", "/usr/local/bin/k9s")),
            Entry(value="~/.local/bin/k9s"),
            Entry(value="/snap/k9s/"),
            Entry(command="aws", standard_paths=("/usr/bin/aws", "/usr/local/bin/aws"), comment="aws eks update-kubeconfig"),
            Entry(value="/usr/local/aws-cli/", comment="aws eks update-kubeconfig"),
            Entry(value="~/google-cloud-sdk/"),
            Entry(value="~/.local/bin/google-cloud-sdk/"),
            Entry(value="/usr/lib/google-cloud-sdk/"),
            Entry(value="/usr/share/google-cloud-sdk/"),
            Entry(value="/snap/google-cloud-cli/"),
        ),
        check_paths=("~/.kube/config",),
    ),
    Watch(
        path="~/.config/gcloud",
        title="GCP credentials",
        entries=(
            Entry(command="gcloud", standard_paths=("/usr/bin/gcloud", "/usr/local/bin/gcloud")),
            Entry(value="~/.local/bin/gcloud"),
            Entry(value="~/google-cloud-sdk/", comment="official archive install in home"),
            Entry(value="~/.local/bin/google-cloud-sdk/", comment="common user-local archive location"),
            Entry(value="/usr/lib/google-cloud-sdk/"),
            Entry(value="/usr/share/google-cloud-sdk/"),
            Entry(value="/snap/google-cloud-cli/"),
            Entry(value="gcloud:~/.pyenv/versions/"),
        ),
    ),
    Watch(
        path="~/.docker",
        title="Docker/Podman auth tokens",
        entries=(
            Entry(command="docker", standard_paths=("/usr/bin/docker", "/usr/local/bin/docker")),
            Entry(value="~/bin/docker", comment="Docker rootless script default"),
            Entry(value="~/.local/bin/docker"),
            Entry(value="/snap/docker/"),
            Entry(command="podman", standard_paths=("/usr/bin/podman", "/usr/local/bin/podman")),
            Entry(value="~/.local/bin/podman"),
            Entry(command="podman-remote", standard_paths=("/usr/bin/podman-remote", "/usr/local/bin/podman-remote")),
            Entry(value="~/.local/bin/podman-remote"),
        ),
        check_paths=("~/.docker/config.json",),
    ),
    Watch(
        path="~/.config/gh",
        title="GitHub CLI auth",
        entries=(
            Entry(command="gh", standard_paths=("/usr/bin/gh", "/usr/local/bin/gh")),
            Entry(value="~/.local/bin/gh"),
            Entry(value="/snap/gh/"),
            Entry(value="~/.local/share/gh/extensions/", comment="gh extensions such as gh-copilot"),
        ),
        check_paths=("~/.config/gh/hosts.yml",),
    ),
    Watch(
        path="~/.password-store",
        title="pass/gopass encrypted store",
        entries=(
            Entry(command="pass", standard_paths=("/usr/bin/pass",)),
            Entry(command="gopass", standard_paths=("/usr/bin/gopass",)),
        ),
    ),
    Watch(
        path="~/.gemini",
        title="Gemini CLI credentials",
        entries=(
            Entry(value="gemini-cli:~/.bun/bin/bun"),
            Entry(value="gemini-cli:~/.nvm/versions/node/", comment="prefix: node via nvm, cmdline must contain \"gemini-cli\""),
        ),
    ),
)


LOCAL_WATCHES: tuple[Watch, ...] = (
    Watch(
        path="~/.claude",
        title="Claude Code config, API keys, memory",
        entries=(
            Entry(value="~/.local/share/claude/versions/", comment="native installer symlink resolves here"),
            Entry(value="~/.local/bin/claude"),
            Entry(value="claude:~/.bun/bin/bun"),
            Entry(value="claude:~/.nvm/versions/node/"),
            Entry(value="claude:/usr/bin/node"),
            Entry(value="claude:/usr/local/bin/node"),
            Entry(value="claude:~/.pyenv/versions/"),
            Entry(command="cursor", standard_paths=("/usr/share/cursor/cursor", "/usr/bin/cursor"), comment="Cursor reads Claude history/context"),
            Entry(value="/opt/cursor/"),
            Entry(value="/usr/bin/bash", comment="Claude Code Bash tool sources shell snapshots"),
            Entry(value="/bin/bash"),
        ),
    ),
    Watch(
        path="~/.cursor",
        title="Cursor editor auth/config",
        entries=(
            Entry(command="cursor", standard_paths=("/usr/share/cursor/cursor", "/usr/bin/cursor")),
            Entry(value="/usr/local/bin/cursor"),
            Entry(value="/opt/cursor/"),
            Entry(value="~/.local/bin/cursor"),
            Entry(value="~/.cursor-server/", comment="Cursor remote server, hash/versioned"),
        ),
    ),
    Watch(
        path="~/.config/Code",
        title="VS Code editor auth/config",
        entries=(
            Entry(command="code", standard_paths=("/usr/share/code/code", "/usr/bin/code")),
            Entry(value="/usr/local/bin/code"),
            Entry(value="/opt/visual-studio-code/code"),
            Entry(value="~/VSCode-linux-x64/code"),
            Entry(value="~/.vscode-oss/bin/code"),
            Entry(value="/snap/code/"),
            Entry(value="com.visualstudio.code:/usr/bin/flatpak"),
        ),
    ),
    Watch(
        path="~/.config/Code - Insiders",
        title="VS Code Insiders editor auth/config",
        entries=(
            Entry(command="code-insiders", standard_paths=("/usr/share/code-insiders/code-insiders", "/usr/bin/code-insiders")),
            Entry(value="/usr/local/bin/code-insiders"),
            Entry(value="/opt/visual-studio-code-insiders/code-insiders"),
            Entry(value="~/VSCode-linux-x64/code-insiders"),
            Entry(value="/snap/code-insiders/"),
            Entry(value="com.visualstudio.code.insiders:/usr/bin/flatpak"),
        ),
    ),
    Watch(
        path="~/.config/Code - OSS",
        title="Code OSS editor auth/config",
        entries=(
            Entry(command="code-oss", standard_paths=("/usr/lib/code-oss/code-oss", "/usr/bin/code-oss")),
            Entry(value="/usr/local/bin/code-oss"),
            Entry(value="~/.vscode-oss/bin/code"),
            Entry(value="~/.vscode-oss/bin/code-oss"),
            Entry(value="com.visualstudio.code-oss:/usr/bin/flatpak"),
        ),
    ),
    Watch(
        path="~/.config/VSCodium",
        title="VSCodium editor auth/config",
        entries=(
            Entry(command="codium", standard_paths=("/usr/share/codium/codium", "/usr/bin/codium")),
            Entry(value="/usr/local/bin/codium"),
            Entry(value="/opt/vscodium-bin/codium"),
            Entry(value="/snap/codium/"),
            Entry(value="com.vscodium.codium:/usr/bin/flatpak"),
        ),
    ),
    Watch(
        path="~/.codex",
        title="OpenAI Codex CLI",
        entries=(
            Entry(value="~/.local/bin/codex"),
            Entry(value="~/.bun/install/global/node_modules/@openai/", comment="npm/bun global package native payloads"),
            Entry(value="codex:~/.bun/bin/bun"),
            Entry(value="codex:~/.nvm/versions/node/"),
            Entry(value="codex:/usr/bin/node"),
            Entry(value="codex:/usr/local/bin/node"),
            Entry(command="git", standard_paths=("/usr/bin/git",), comment="codex clones plugins into ~/.codex/.tmp/"),
            Entry(value="/usr/local/bin/git"),
            Entry(value="/usr/lib/git-core/git", comment="git subprocess"),
            Entry(value="/usr/lib/git-core/git-remote-http", comment="git-remote-https is same binary"),
            Entry(value="/usr/lib/git-core/git-remote-https"),
            Entry(value="/usr/libexec/git-core/git"),
            Entry(value="/usr/libexec/git-core/git-remote-http"),
            Entry(value="/usr/libexec/git-core/git-remote-https"),
            Entry(command="cursor", standard_paths=("/usr/share/cursor/cursor", "/usr/bin/cursor"), comment="Cursor reads Codex history/context"),
            Entry(value="/opt/cursor/"),
            Entry(value="/usr/bin/bash", comment="codex shell snapshots"),
            Entry(value="/bin/bash"),
        ),
    ),
    Watch(
        path="~/.opencode",
        title="Opencode config",
        entries=(
            Entry(value="~/.opencode/bin/opencode"),
            Entry(value="~/.local/bin/opencode"),
            Entry(value="~/.bun/install/global/node_modules/@opencode-ai/"),
            Entry(value="opencode:~/.bun/bin/bun"),
            Entry(value="opencode:~/.nvm/versions/node/"),
            Entry(value="opencode:/usr/bin/node"),
            Entry(value="opencode:/usr/local/bin/node"),
        ),
    ),
)


OPTIONAL_WATCHES: tuple[Watch, ...] = (
    Watch(
        path="~/.cargo-for-the-paranoid",
        title="Cargo credentials",
        entries=(
            Entry(value="~/.cargo/bin/cargo"),
            Entry(value="~/.cargo/bin/rustup"),
            Entry(value="/usr/bin/cargo"),
            Entry(value="/usr/bin/rustup"),
            Entry(value="/usr/local/bin/cargo"),
            Entry(value="/usr/local/bin/rustup"),
            Entry(value="cursor-shellIntegration-bash.sh:/usr/bin/bash", comment="Cursor shell integration reads ~/.cargo/env"),
        ),
        always_render=True,
    ),
    Watch(
        path="~/.config/git-for-the-paranoid",
        title="Git credential storage",
        entries=(
            Entry(command="git", standard_paths=("/usr/bin/git", "/usr/local/bin/git")),
            Entry(value="/usr/lib/git-core/git"),
            Entry(value="/usr/lib/git-core/git-remote-http"),
            Entry(value="/usr/lib/git-core/git-remote-https"),
            Entry(value="/usr/libexec/git-core/git"),
            Entry(value="/usr/libexec/git-core/git-remote-http"),
            Entry(value="/usr/libexec/git-core/git-remote-https"),
            Entry(value="/usr/local/share/git-core/git"),
            Entry(value="/usr/local/share/git-core/git-remote-http"),
            Entry(value="/usr/local/share/git-core/git-remote-https"),
            Entry(value="~/.local/share/claude/versions/", comment="Claude Code may read gitignore/config"),
            Entry(command="cursor", standard_paths=("/usr/share/cursor/cursor", "/usr/bin/cursor"), comment="Cursor may read git config/history"),
            Entry(value="/opt/cursor/"),
        ),
        always_render=True,
    ),
    Watch(
        path="~/.pki-for-the-paranoid",
        title="NSS certificate database / TLS client certificates",
        entries=(
            Entry(value="/usr/bin/firefox"),
            Entry(value="/usr/lib/firefox/firefox"),
            Entry(value="/usr/lib64/firefox/firefox"),
            Entry(value="/snap/firefox/"),
            Entry(value="/usr/bin/google-chrome"),
            Entry(value="/usr/bin/google-chrome-stable"),
            Entry(value="/opt/google/chrome/chrome"),
            Entry(value="/opt/google/chrome/google-chrome"),
            Entry(value="/usr/bin/chromium"),
            Entry(value="/usr/bin/chromium-browser"),
            Entry(value="/usr/lib/chromium/chromium"),
            Entry(value="/usr/lib64/chromium-browser/chromium-browser"),
            Entry(value="/snap/chromium/"),
            Entry(value="/usr/bin/brave-browser"),
            Entry(value="/opt/brave.com/brave/brave"),
            Entry(value="/usr/bin/certutil"),
            Entry(value="/usr/bin/pk12util"),
        ),
        always_render=True,
    ),
)


def expand_user(path: str) -> Path:
    if path == "~":
        return HOME
    if path.startswith("~/"):
        return HOME / path[2:]
    return Path(path)


def path_exists(path: str) -> bool:
    return expand_user(path.rstrip("/")).exists()


def should_render_watch(watch: Watch, ctx: RenderContext) -> bool:
    return ctx.default_template or watch.always_render or path_exists(watch.path)


def readlink_f(path: str) -> str:
    return os.path.realpath(os.path.expanduser(path))


def which(command: str) -> str | None:
    found = shutil.which(command)
    if found is None:
        return None
    return readlink_f(found)


def prefixed(value: str, entry: Entry) -> str:
    rendered = value + entry.suffix
    if entry.filter:
        rendered = f"{entry.filter}:{rendered}"
    return rendered


def resolve_default_entries(entry: Entry) -> list[RenderedEntry]:
    if entry.value is not None:
        return [RenderedEntry(entry.value, True, entry.comment)]

    if entry.command is None:
        raise ValueError("entry must define value or command")

    paths = entry.standard_paths or (f"/usr/bin/{entry.command}",)
    return [RenderedEntry(prefixed(path, entry), True, entry.comment) for path in paths]


def resolve_entry(entry: Entry, watch: Watch, ctx: RenderContext) -> RenderedEntry:
    if entry.value is not None:
        active = path_exists(entry.value) if entry.value.startswith(("~", "/")) else path_exists(entry.value.split(":", 1)[-1])
        return RenderedEntry(entry.value, active, entry.comment if active else entry.missing_comment)

    if entry.command is None:
        raise ValueError("entry must define value or command")

    for standard_path in entry.standard_paths:
        if Path(standard_path.rstrip("/")).exists():
            return RenderedEntry(prefixed(readlink_f(standard_path), entry), True, entry.comment)

    discovered = which(entry.command)
    if discovered is not None:
        warning = (
            f"{watch.path}: {entry.command} resolved to non-standard path {discovered}; "
            f"standard paths checked: {', '.join(entry.standard_paths)}"
        )
        ctx.warn(warning)
        comment = "WARNING: non-standard path found via PATH"
        if entry.comment:
            comment = f"{entry.comment}; {comment}"
        return RenderedEntry(prefixed(discovered, entry), True, comment)

    missing = entry.standard_paths[0] if entry.standard_paths else f"/usr/bin/{entry.command}"
    return RenderedEntry(prefixed(missing, entry), False, entry.missing_comment)


def quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_entry(entry: RenderedEntry) -> str:
    prefix = "    " if entry.active else "    # "
    line = f"{prefix}{quote(entry.value)},"
    if entry.comment:
        line += f"  # {entry.comment}"
    return line


def dedupe_key(value: str) -> str:
    filter_prefix = ""
    path_part = value
    if ":" in value and not value.startswith("/"):
        filter_value, path_part = value.split(":", 1)
        filter_prefix = f"{filter_value}:"

    profile_suffix = ""
    if ";" in path_part:
        path_part, profile_name = path_part.split(";", 1)
        profile_suffix = f";{profile_name}"

    trailing_slash = path_part.endswith("/")
    if path_part.startswith(("~", "/")):
        path_part = str(expand_user(path_part.rstrip("/")))
        if trailing_slash:
            path_part += "/"

    return f"{filter_prefix}{path_part}{profile_suffix}"


def render_watch(watch: Watch, ctx: RenderContext) -> str:
    lines = [f"# --- {watch.title} ---", f"{quote(watch.path)} = ["]
    rendered_entries: list[RenderedEntry] = []
    seen: set[str] = set()
    for entry in watch.entries:
        entries = resolve_default_entries(entry) if ctx.default_template else [resolve_entry(entry, watch, ctx)]
        for rendered in entries:
            key = dedupe_key(rendered.value)
            if key in seen:
                continue
            seen.add(key)
            rendered_entries.append(rendered)
    lines.extend(render_entry(entry) for entry in rendered_entries)
    lines.append("]")
    return "\n".join(lines)


def render_section(title: str, watches: Iterable[Watch], ctx: RenderContext) -> str:
    blocks = [render_watch(watch, ctx) for watch in watches if should_render_watch(watch, ctx)]
    if not blocks:
        return title
    return title + "\n\n" + "\n\n".join(blocks)


def render_config(ctx: RenderContext) -> str:
    common = render_section(COMMON_SECTION, COMMON_WATCHES, ctx)
    local = render_section(LOCAL_SECTION, LOCAL_WATCHES, ctx)
    optional = render_section(OPTIONAL_SECTION, OPTIONAL_WATCHES, ctx)
    optional_note = (
        "# Cargo stores plaintext tokens at $CARGO_HOME/credentials.toml by default,\n"
        "# but standard Rust installs put cargo/rustup under ~/.cargo/bin. Watching\n"
        "# ~/.cargo can block shells from launching those tools before /proc/pid/exe\n"
        "# becomes cargo or rustup. Prefer Cargo credential providers instead:\n"
        "# https://doc.rust-lang.org/cargo/reference/registry-authentication.html\n"
        "# https://doc.rust-lang.org/cargo/reference/credential-provider-protocol.html\n"
        "# Linux mitigation: configure cargo:libsecret so tokens live in a keyring.\n"
        "# To enable this watch anyway, rename \"~/.cargo-for-the-paranoid\" to \"~/.cargo\".\n"
    )
    optional = optional.replace("# --- Cargo credentials ---", optional_note + "# --- Cargo credentials ---")
    optional_note = (
        "# ~/.config/git can contain credential helpers or credential files, but many\n"
        "# apps read ~/.config/git/gitignore and config, so it is high-noise. To enable\n"
        "# it, rename the key from \"~/.config/git-for-the-paranoid\" to \"~/.config/git\".\n"
    )
    optional = optional.replace("# --- Git credential storage ---", optional_note + "# --- Git credential storage ---")
    optional_note = (
        "# This can be sensitive if you store client certificates or private keys in NSS,\n"
        "# but browsers and Electron apps hit it frequently. To enable it, rename the key\n"
        "# from \"~/.pki-for-the-paranoid\" to \"~/.pki\".\n"
    )
    optional = optional.replace("# --- NSS certificate database / TLS client certificates ---", optional_note + "# --- NSS certificate database / TLS client certificates ---")
    header = DEFAULT_HEADER if ctx.default_template else HOST_HEADER
    return header + common + "\n\n" + local + "\n\n" + optional + "\n"


def backup_base_for(path: Path) -> Path:
    if path == OUTPUT:
        return CONFIG_DIR / "dirblock_orig.toml"
    return path.with_name(f"{path.stem}_orig{path.suffix}")


def next_backup_path(path: Path) -> Path:
    backup_base = backup_base_for(path)
    if not backup_base.exists():
        return backup_base

    index = 1
    while True:
        candidate = backup_base.with_name(f"{backup_base.stem}_{index}{backup_base.suffix}")
        if not candidate.exists():
            return candidate
        index += 1


def write_config(path: Path, ctx: RenderContext) -> tuple[Path | None, bool]:
    rendered = render_config(ctx)
    if path.exists():
        existing = path.read_text(encoding="utf-8")
        if existing == rendered:
            return None, False

        backup = next_backup_path(path)
        shutil.copy2(path, backup)
    else:
        backup = None

    path.write_text(rendered, encoding="utf-8")
    return backup, True


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate deterministic dirblock configuration.")
    parser.add_argument(
        "--default",
        action="store_true",
        help="generate the broad open-source template at config/dirblock_default.toml",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        help="override output path",
    )
    return parser.parse_args()


def display_path(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def main() -> int:
    args = parse_args()
    ctx = RenderContext(default_template=args.default)
    output = args.output or (DEFAULT_OUTPUT if args.default else OUTPUT)
    if not output.is_absolute():
        output = ROOT / output

    CONFIG_DIR.mkdir(exist_ok=True)
    output.parent.mkdir(parents=True, exist_ok=True)
    backup, wrote = write_config(output, ctx)

    if backup is not None:
        print(f"backed up existing config to {display_path(backup)}")
    if wrote:
        print(f"wrote {display_path(output)}")
    else:
        print(f"unchanged {display_path(output)}")
    if ctx.warnings:
        print("\nwarnings:", file=sys.stderr)
        for warning in ctx.warnings:
            print(f"  WARNING: {warning}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
